baseurl: https://mpdesouza.com/
languageCode: en
title: Marcos Souza
theme: soho
summarylength: 10
paginate: 10

enableEmoji: true
enableRobotsTXT: true

# googleAnalytics: UA-1234-1
# disqusShortname: mpdesouza

params:
  mainSections:
    - posts

  images:
    - https://www.gravatar.com/avatar/1234?s=400&d=mp

  author: Marcos Paulo de Souza
  description: Things about Linux
  # themeColor: "#fc2803"
  # description:
  gravatar: foo@mpdesouza.com

  copyright: Marcos Paulo de Souza
  license: CC BY-SA 4.0
  licenseURL: https://creativecommons.org/licenses/by-sa/4.0

  socialIcons:
    - icon: fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/marcospsouza
    - icon: fa-twitter
      title: Twitter
      url: https://twitter.com/omarcossouza
    - icon: fa-github
      title: GitHub
      url: https://github.com/marcosps


  # customCss:
  #   - '#'

  # customJs:
  #   - '#'

taxonomies:
  category: categories
  series: series
  tag: tags

menu:
  main:
  # - name: Posts
  #   weight: 100
  #   identifier: posts
  #   url: /posts/
  - name: About Me
    identifier: about
    weight: 200
    url: /about-me/

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 4
